name: scan
description: TCC Willian Varela

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_picker: ^0.6.6+1 # Câmera/Galeria
  tflite: ^1.1.1 # Tensorflow mobile
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/